language: node_js
node_js:
  - "node"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure:
  app: travis-ci-test-sm
  on:
    repo: stephaniemagdic/travis-ci-test-sm
    branch: main
env: